# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20170712_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='update',
            new_name='updated',
        ),
    ]
