# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20170712_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='my_date_field',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
